Adding ADRs to the project
jenshaase/phel-lang pull request #124
Opened 2020-11-04 11:06 UTC by Chemaclass

## 📚 Description

An architectural decision record (ADR) is a document that captures an important architectural decision made along with its context and consequences.

You can read more about them here -> https://github.com/joelparkerhenderson/architecture_decision_record

## 🔖 Changes

- Introduced an ADR directory with a template an a real example of it

2020-11-17 17:02 UTC, jenshaase commented
OK, thanks for bringing this up. I know how useful this can be. I introduced RFCs to my company recently and it helps us to bring more structure to our code. However, the more important thing with ADRs or RFCs is the process on how they are created, discussed, processed and so forth. Just adding ADR file will not make a difference. Additionally, we need a way to track if all ADRs are full filled when new code is added or changed.

I would recommend following process:
1. An ADR or RFC can be proposed with an issue.
2. The issue is the place to discuss everything
3. The result of the issue can be an ADR file, but also just as CS Fixer rule to check then during CI.

What do you think?

Regarding the Doc Comment issue. This can be done by using the `phpdoc_line_span` rule of the CS Fixer:
```
./vendor/bin/php-cs-fixer describe phpdoc_line_span
```

2020-11-18 06:44 UTC, Chemaclass commented
Yes, a pretty good idea: raising an issue for an open discussion and write down as an ADR (or defining a cs fixer; or whatever that applies to the result) the conclusions of the proposal.

About the doc comment, you're right, I didn't know that one https://mlocati.github.io/php-cs-fixer-configurator/#version:2.16|fixer:phpdoc_line_span.

And concerning this actual PR, what about:
1) I will remove the `adrs/0001_phpdocs.md` (this will be part of another PR, where I will introduce that ADR + the [phpcs rule](https://mlocati.github.io/php-cs-fixer-configurator/#version:2.16|fixer:phpdoc_line_span)).
2) I will create a `adrs/README.md` with the information that we gathered here about how do we want to work with ADRs and its process.

Is it fine for you or do you have something else in mind?

2020-12-01 12:56 UTC, jenshaase commented
I would put the information in the main Readme file (not in `adrs/README.md`).

2020-12-01 15:11 UTC, Chemaclass commented
Right, good point. I will create later a PR doing that 👍🏼

2020-12-06 15:42 UTC, jenshaase requested changes
Not really happy yet. I added some comments.

2020-12-06 15:42 UTC, jenshaase commented on Readme.md
> +### Architecture Decision Record (ADR)
I think this section should no be called ADR. ADR is one of the results that could happen. I would call it "Substantial changes".

Also: Move this to the contribution section.

2020-12-06 15:42 UTC, jenshaase commented on Readme.md
> +These helps us to bring more structure to our code. However, the most important thing with ADRs or RFCs is the process
It should start with an Introduction to what "Substantial changes" are and what they are not. Substantial changes are architecture decisions, documentation restructuring, breaking changes, etc. But not Bug Reports, Bug Fixes, Unit Tests, etc.

2020-12-06 15:42 UTC, jenshaase commented on Readme.md
> +#### Adding an ADR Process
I would call this "How to contribute a substantial change".

2020-12-06 15:42 UTC, jenshaase commented on Readme.md
> +
Add an introduction: "In order to make a substantial change it is a good practice to discuss the idea before implementing it. ..." (or similar)

2020-12-06 15:42 UTC, jenshaase commented on adrs/0000_adr_template.md
> +(proposed, accepted, rejected, deprecated, etc.)
If an ADR is the result of an issue, it doesn't need any kind of state.

2020-12-06 15:42 UTC, jenshaase commented on adrs/0000_adr_template.md
> +## Context
Rename to Motivation

2020-12-13 21:46 UTC, Chemaclass commented
@jenshaase is it ok now? or would you like to modify something else? :)

2020-12-14 14:51 UTC, jenshaase requested changes
Small change left

2020-12-14 14:51 UTC, jenshaase commented on Readme.md
> +- An ADR or RFC can be proposed with an issue.
For people unfamiliar with abbreviations of ADR and RFC it would be good to define them as full form first:
"Architecture Decision Record (ADR)".

2020-12-15 14:29 UTC, jenshaase approved these changes
Super! I will merge it.

2020-12-15 14:29 UTC, merged