Refactored Main and IntegrationTest
jenshaase/phel-lang pull request #127
Opened 2020-12-03 20:54 UTC by Chemaclass

# Description

I clean up a bit more of the main entry point and minor improvements as well.

# Changes

- Clean up the `phel` script and the Main class
- Created CompilerFactoryInterface & CommandFactoryInterface
- Clean up the IntegrationTest logic in order to use the CompilerFactory

2020-12-05 17:17 UTC, jenshaase requested changes
Only a small change is required!

2020-12-05 18:44 UTC, Chemaclass commented on phel
> +$currentDir = __DIR__ . $slash;
Yeah, I was thinking but I wasn't sure about that... thanks for that catching, I will update it. Thanks!

2020-12-05 18:48 UTC, JesusValera approved these changes

2020-12-06 09:29 UTC, jenshaase approved these changes

2020-12-06 09:29 UTC, merged