[WIP] Add suffixes & prefixes to Lang classes
jenshaase/phel-lang pull request #147
Opened 2021-01-01 16:47 UTC by JesusValera

## 📚 Description

Check `Lang` folder and update class names... 😃 

@todo: Missing to add the `ADR` file...

## 🔖 Changes

- Rename `I{Class}` to `{Class}Interface`
- Rename `T{Class}` to `Trait{Class}`
- Rename `A{Class}` to `Abstract{Class}`
  - Also, rename abstract `Struct` class to `AbstractStruct`*

## ⚠️ INFO

I renamed the `Struct` class to `AbstractStruct` as we agreed on https://github.com/jenshaase/phel-lang/issues/145
I think renaming the class doesn't affect the `Phel` code per se, but just to be sure I would like to know your opinion @jenshaase.

2021-01-01 17:04 UTC, jenshaase commented
Changes look good. Struct should still work.

2021-01-02 10:38 UTC, jenshaase requested changes
Can we move this to `/adrs/php`. Then we have the option to make a `/adrs/phel` directory later.

2021-01-03 12:10 UTC, Chemaclass approved these changes

2021-01-03 12:12 UTC, jenshaase approved these changes

2021-01-03 12:12 UTC, merged

2021-01-03 12:12 UTC, jenshaase commented
Cool! It is merged now!