Refactor FnAsClassEmitter
jenshaase/phel-lang pull request #163
Opened 2021-01-10 16:29 UTC by Chemaclass

## 🔖 Changes

- Refactored the `FnAsClassEmitter` class
- Added unit tests for it

2021-01-10 16:58 UTC, JesusValera approved these changes
Super clear what this class does with the tests. 👍🏼👍🏼

2021-01-11 06:55 UTC, jenshaase requested changes
Only a small naming thing. Otherwise it looks very good!

2021-01-11 06:55 UTC, jenshaase commented on src/php/Compiler/Analyzer/Ast/PhpVarNode.php
> +        $returnNode = NodeEnvironment::empty()
`$returnNode` should be called `$returnEnv` or just `$env`

2021-01-11 08:23 UTC, jenshaase approved these changes

2021-01-11 08:23 UTC, merged

2021-01-11 08:24 UTC, jenshaase commented
Thanks! It is merged now!