Adding unit tests to TextExceptionPrinter
jenshaase/phel-lang pull request #178
Opened 2021-01-17 12:43 UTC by Chemaclass

## 📚 Description

I did some refactoring for the "Exception Printers" in order to be able to write some unit tests for them.

## 🔖 Changes

- Created an `ExceptionPrinterTrait` which contains the duplicated functions from both ExceptionPrinters.
- Created some interfaces in order to decouple the ExceptionPrinters from their direct dependencies.

I was not able to unit test the `FilePositionExtractor` for "SourceMapComment" case (See it in `FilePositionExtractorTest`). There is still some coupling there with the `SourceMapConsumer`, but I didn't want to go deeper. We might go there in another iteration. I think this one is more than good enough for a PR itself :)

2021-01-17 20:02 UTC, jenshaase commented
I'm unsure about the naming of `CommentExtractor`. It extracts basically the original file name and the source map data from the file. Maybe a better name would be `SourceMapExtractor`. What do you think?

2021-01-18 06:31 UTC, Chemaclass commented
@jenshaase, right. I will rename it, thanks

2021-01-18 07:59 UTC, jenshaase requested changes
Sorry, I probably was a bit unclear in my last comment :) 
But can you also please rename the interface and method names :)

2021-01-18 07:59 UTC, jenshaase commented on src/php/Exceptions/Extractor/CommentExtractorInterface.php
> +interface CommentExtractorInterface
The interface needs to be renamed too.

2021-01-18 07:59 UTC, jenshaase commented on src/php/Exceptions/Extractor/CommentExtractorInterface.php
> +    public function getExtractedComment(string $fileName): ExtractedComment;
And the method name.

2021-01-18 07:59 UTC, jenshaase commented on src/php/Exceptions/Extractor/ReadModel/ExtractedComment.php
> +final class ExtractedComment
This should be renamed to `SourceMapInformation`

2021-01-18 14:51 UTC, jenshaase approved these changes

2021-01-18 14:51 UTC, merged

2021-01-18 14:51 UTC, jenshaase commented
Look good now. Thank you for that!